version: 1
authorized_values:
  itemtypes:
    F1_Z1_K1: "Статті"
    F1_Z1_K2: "Дисертації"
    F2_Z3_K3: "Рукописи"
    
  ccodes:
    FICTION: "Художня література"
    SCIENCE: "Наукова література"

unknown_policy:
  authorized_value: "keep_code"
